# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QZShortVideo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QZShortVideo
  pod 'TZImagePickerController',:git =>'https://github.com/banchichen/TZImagePickerController.git',:inhibit_warnings => true

  target 'QZShortVideoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QZShortVideoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
